// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0PurcoY9jc8zIee_cKv_St1M4sW3luFA',
    appId: '1:457683112054:web:c4989dfb108aaf6ad80f57',
    messagingSenderId: '457683112054',
    projectId: 'fir-cli-d1942',
    authDomain: 'fir-cli-d1942.firebaseapp.com',
    storageBucket: 'fir-cli-d1942.appspot.com',
    measurementId: 'G-YPNS5G6HNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_sB2K7ca-1GZSN4H0rhdF4HRSSNkU9jk',
    appId: '1:457683112054:android:83e9f68454dd6597d80f57',
    messagingSenderId: '457683112054',
    projectId: 'fir-cli-d1942',
    storageBucket: 'fir-cli-d1942.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2krYh5RrTOSygT9926ROReHx29s4ReTY',
    appId: '1:457683112054:ios:3a45f6d2a02758c8d80f57',
    messagingSenderId: '457683112054',
    projectId: 'fir-cli-d1942',
    storageBucket: 'fir-cli-d1942.appspot.com',
    iosClientId: '457683112054-7ih8ep6q9ivqfnpicvtho45h3liqpf0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireabaseCli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2krYh5RrTOSygT9926ROReHx29s4ReTY',
    appId: '1:457683112054:ios:3a45f6d2a02758c8d80f57',
    messagingSenderId: '457683112054',
    projectId: 'fir-cli-d1942',
    storageBucket: 'fir-cli-d1942.appspot.com',
    iosClientId: '457683112054-7ih8ep6q9ivqfnpicvtho45h3liqpf0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireabaseCli',
  );
}
